const express = require("express");
const cors = require("cors");
const router = express.Router();
router.use(cors());
const { OwnerRegistration } = require("../Controllers/OwnerRegistration");
const { OwnerLogin } = require("../Controllers/OwnerLogin");
const { AddHostel } = require("../Controllers/AddHostel");
const { GetHostel } = require("../Controllers/GetHostel");
const { DeleteHostel } = require("../Controllers/AddHostel");
const { OwnerForgetPassword } = require("../Controllers/ForgetPassword");
const { OwnerResetPassword } = require("../Controllers/ResetPassword");
const { DashBoardOwner } = require("../Controllers/OwnerDashboard");
const { UpdateHostel } = require("../Controllers/UpdateHostel");
router.post("/ownerSignup", OwnerRegistration);
router.post("/ownerLogin", OwnerLogin);
router.post("/hostelData", AddHostel);
router.get("/getHostel", GetHostel);
router.delete("/getHostel/:id", DeleteHostel);
router.post("/ownerForgetPassword", OwnerForgetPassword);
router.post("/ownerResetPassword/:id/:token", OwnerResetPassword);
router.post("/dashBoardOwner", DashBoardOwner);
router.put("/hostelUpdate/:id", UpdateHostel);
// const { SearchHostel } = require("../Controllers/SearchHostel");
// router.post("/book", BookingHostel);
// router.post("/forgetPassword", ForgetPassword);
// router.post("./search", SearchHostel);
module.exports = router;
