const express = require("express");
const cors = require("cors");
const router = express.Router();
router.use(cors());
const { OwnerRegistration } = require("../Controllers/OwnerRegistration");
router.post("/ownerSignup", OwnerRegistration);
const { OwnerLogin } = require("../Controllers/OwnerLogin");
router.post("/ownerLogin", OwnerLogin);
const { AddHostel } = require("../Controllers/AddHostel");
router.post("/hostelData", AddHostel);
const { GetHostel } = require("../Controllers/GetHostel");
router.get("/getHostel", GetHostel);
// const { ResetPassword } = require("../Controllers/ResetPassword");
// const { SearchHostel } = require("../Controllers/SearchHostel");
// router.post("/book", BookingHostel);
// router.post("/forgetPassword", ForgetPassword);
// router.post("/resetPassword/:id/:token", ResetPassword);
// router.post("./search", SearchHostel);
module.exports = router;
